apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-db-vault
spec:
  selector:
    matchLabels:
      app: sample-app-db-vault
  template:
    metadata:
      labels:
        app: sample-app-db-vault
    spec:
      containers:
        - name: sample-app-db-vault
          image: piomin/sample-app:1.1-gitops
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/config/application.yml
          volumeMounts:
            - mountPath: /opt/config
              name: config
      volumes:
        - name: config
          configMap:
            name: sample-app-db-vault
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-db-vault
spec:
  type: ClusterIP
  selector:
    app: sample-app-db-vault
  ports:
    - port: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  name: sample-app-db-vault
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: sample-app-db-vault
    weight: 100
  wildcardPolicy: None