projects:
  - name: pminkows-test
    managedBy: pminkows-cicd
    group: app-owners
  - name: pminkows-stage
    managedBy: pminkows-cicd
    group: app-owners
  - name: pminkows-prod
    managedBy: pminkows-cicd
    group: app-owners
    quotas:
      pods: '8'
      memoryRequest: 4Gi
      memoryLimit: 10Gi
  - name: pminkows-cicd
    group: app-owners
    quotas:
      pods: '20'
      cpuRequest: '4'
      memoryRequest: 4Gi
      cpuLimit: '20'
      memoryLimit: 20Gi
    default:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi
cicdOwner: true
addUsers: true
