kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admins
users:
  - opentlc-mgr
  - admin
  - tech-admin
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cicd-admins
users:
  - piomin
  - user1
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: app-owners
users:
  - pminkows
  - user2
{{- if .Values.cicdOwner }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-admins-access
  namespace: openshift-gitops
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cicd-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}