{{- range .Values.projects }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
  namespace: {{ .name }}
spec:
  limits:
    - default:
        memory: {{ (.default).limits.memory | default "512Mi" }}
        cpu: {{ (.default).limits.cpu | default "500m" }}
      defaultRequest:
        memory: {{ (.default).requests.memory | default "256Mi" }}
        cpu: {{ (.default).requests.cpu | default "250m" }}
      type: Container
{{- end }}