{{- range .Values.projects }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: {{ .name }}
spec:
  hard:
    pods: {{ (.quotas).pods | default "10" }}
    requests.cpu: {{ (.quotas).cpuRequest | default "2" }}
    requests.memory: {{ (.quotas).memoryRequest | default "2Gi" }}
    limits.cpu: {{ (.quotas).cpuLimit | default "8" }}
    limits.memory: {{ (.quotas).memoryLimit | default "8Gi" }}
---
{{- end}}