{{- range .Values.projects }}
{{- if .group }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-access
  namespace: {{ .name }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .group }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
{{- end }}
{{- end }}