{{- if .Values.addUsers }}
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: dXNlcjE6JDJ5JDA1JHo2d05sQmhrNGlJLnQ0ZjJCSm1lV3VwYXpnQllwWWExb3pTNlR5Q1M4L3lrQ01XNDlLWENtCnVzZXIyOiQyeSQwNSRzRVh5RWRHby5tWmtTNDNlbnlHc0V1aC9aSWF3VnJiRmlwak1CYnVyNjQxZ2pCWlRjVHAwZQp1c2VyMzokMnkkMDUkMlU4cmx0WW5XQzZvcHRrQ1ZoZFpudXFMd1hTeXAyUGdkclNaTG84Q2pLU2ZveTRhNDhXUUMKdXNlcjQ6JDJ5JDA1JHFZSHV5bVlwSTVtYjAwdnAvS0IyWi43L3JRN2hCaHltckhLWnFneHNsQWpRSGowaE9JdlNTCnVzZXI1OiQyeSQwNSRYU3hLd2F2UHJsMjhtbGhpS21xRm9PQ1lzcE5OZmJ1TW9qVmlmQ1lZOEkwcUVSdjk1ZFpwdQpwbWlua293czokMnkkMDUkRVVUVzVRQjJQTnp5enhSWXFJazczT2pqNjJjajhGWEc1d2pBQUcwUWQ0NjE2UEMzUmJJTGkKdGVjaC1hZG1pbjokMnkkMDUkSG9rMHlqWWs0cjJkYThvSDFic0RuZXFQTDQzcGVJVzFsdFhXN1VWSlM5YkRjcjlUeFlSZmk=
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - name: my_htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpass-secret
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-generated-secret
  namespace: openshift-gitops
spec:
  patches:
    patchPipelineAccount:
      patchTemplate: |
        metadata:
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Prune=false
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          name: openshift-gitops
          kind: Namespace
        - apiVersion: v1
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops
          kind: ServiceAccount
      targetObjectRef:
        apiVersion: v1
        name: v4-0-config-user-idp-0-file-data
        namespace: openshift-authentication
        kind: Secret
  serviceAccountRef:
    name: openshift-gitops-argocd-application-controller
{{- end }}