apiVersion: v1
kind: Namespace
metadata:
  name: interconnect
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    skupper.io/type: connection-token-request
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: token-req
  namespace: interconnect
  