apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-secret-token
  namespace: pminkows-cicd
spec:
  encryptedData:
    sonar-project.properties: AgCpbs73oFamikbfmeWf6Tb1MVO1zr7tdcHAZ3gXjnQX9KVC6jLdF5MX/8JVD8+s5raLaRXiPn9LzQxws6ikuGzz4z5p97FDx9/NkeuEuTepUrIquMsOKMJliltY4zRq29iRb6lKF7SPFVBpOLxQT9Ifi3Ld+UO9h9SKlXLzfL+2/9a4+KEgB1QFT1Y5V0dKO3GhPzzpXzAtmLy5CULHNqPOIr4toASTLxd//Fvfzpfxv+7XBrfSwNyh2Yerdt9EGYH7UzKXLpJHiSjGDB5aDarDj65a0stI4CX1Rvw5ngNFFds18N0nLWnzVq0rSUHgb6y6zveLpNkEOpP3BWvGH9P2nN+P8gbT1iwMGlvB9GUNEI6M2OMTWxp/dvEBIdERGwLYs2Vq9I4YyP2VsyAu3NoJTaEzHcKiB7VDAVQghkXZ/O2eMFm8yC811w/+JKORm60F4dbKqPEswNWcLdenVrsw70gdo75jAaJtOh75/r7FZzP33rAD9bgPtKJo8jRMKJFlIDyfZ+KnNvkstVtJq9YRrcqJLODZv9vdbgJDvA0GU0iT7nW1Of0BqfM/2wb2UHCUEMlFhY0eYJZgOVrN2Zg7EVR+iGjselG3F2wde4LF+OHnRhZi8cxe2hBoWFNXQ07e4C+VQEcmIztCNSNlF6hCMQhNNsn/q7vSDICe/LXPhhF3fdvjKNnfGwS9gnGbTQkxum2mRfs1QIiOEyUEApod87A4OjfYeRP/2qX/kk+Hmwagy1Sl0VEfui4ki3TziEurdsWvpjoTFcgbIGnYoXZLr9c0cmScHdG7SuHH5wKm5HGdl1icqxURv+KBm0sCaTlxPmgoyNwKK/EpaA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-secret-token
      namespace: pminkows-cicd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-registry-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBJYSyiexv+fFQq1MFebiveKf7I2QAG4ImpRXBN6Xt6wNxzyleQZr0q55QGHikSUX26viipD32kliHnC1uiQlJWrRYXMtPlxEh7Ll75rWoz7UW+StlHgJi4j5tK0Eu17wz1WM/n9/OhCB7rWm9Xv9YmxRgQ1qivC1udWfoE7Juyn6fsxZCpPX7KgKMPUzifDmgbqAUfrQguqBZJ9izkQwv9wV1756asElSoB7qQBmLwONhxsKpRrm4/peoi7w4zggTNs9Mekd7tvdoo+ku99O7V5Vz79wMRgDd8dAFQhq/xXW5FfYqLgMODVtg4Z7T6Wh9EE/Ia26F+RXoOoNGB4hLXq3UrtoTT/9KNxpwLtWdelgqv2z4VHg+8V+0/Ffpl/UmdK/PQWa4SenfP03GrSCFCpMKG9fu8FiFzmgysPpgnynczojy+GFbo8aO7GDURmXSlM6Jd7jE1knpwiYvLGGR+WSmNuLncJ0BisnUV66MLuN9EI8VtCzOqiP4/uxRnPXfxMj8LOmxpRy6UhSCeoFfCZA/md4ehqXJkbT8qyJSZP4NIGDkCSxaN77FvGEc66+0arFH0+QgKafeZ/7RdKlBJjQ/j0y69tONvZiCcDyIkw6yr+uDIucpSoT7iPWF0AojD+PAnaEhPb1Qw92oYw5dzf5Fde6VJlMDuVXqzEZeGgxILL+6kFFmn3vEDrSijn5Wwv4BL+RTtfpKk6+iLrBWI79ViR3GMviI41G1ZtE0CECvoM9FHh+mITQZoWlQCM2/SFM83i5f6z4F0LMxV0PIFpfhgmI1CPUiekvdFpPumjl6GuFSoUScImb7ToEkFWs9EgsBS3Hj6UbZFbuO3fSIdiVREHZkub/PSzFTMw6pJREvy7qCOc6zAN7qCkiKlhozr5WSGnUEkGosvS0b1ebo6DO68Xc81XR/gi7nlFPwtoGD0ePZ7GtkyNSjP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: quay-registry-secret
      namespace: pminkows-cicd
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jira-token-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    token: AgCnWHIYhYkQ70BIIUtBy+Bq7ONbwLiqeZZZQ6I7Vs4jdlq0w7RwWwjC2kbD3iDhzyP05ord+0WwSrGwu7lSfqHtaG+NcwLfZ9vBSJucxsZKNdjyVJhRIzFUwBFW5VUWihe1Fdi1oUlBDOjFgZuwQ/ZwNro2FAMhl/zQGP1bPHrzdRwL7Aw+FsYai+0E+OG+ztX3hj25ZT4Lcpos6jPieBBWJOW1p2zxJZLXSdKMKguOjerVz+UWZk0ynElTwFoCjGqG5O1Ctwy/MGa00atQ6vmHum5yXwd00DNbYJOnQPNDBF9QIgVS8YClstXK1KSEyvc5ilk3u/cebWTZipZbikRHUlW/H458+T9nF50IFaxAh/eG4XMbU7O8hnluI/YjWUVEA54QlP6/zOITwwIQuHIgVgt8nqPa+cHwhcQrSRetUdWqC6yyCvl0e9wOm4BpwxfnWsdDqUBBHNi5o4V4BdsICWMuGrHFulhUdSfq13WRQAG33LOyX7cVTiVBMfpaeCbBdRmhZ/06T9mHlU+ngUlTZzCEJegHQBawwh2r/vt12NpL2NS9m5qST72ik1w0qElTzkMHJxbzpovmzV0bw5QlZ3hAavvzHQg9s6UaS3IGcYM3ObW5KZfQ1LdwOOBr88J/ckN+ZQmmIXGDufUBgBz6e+JsCqkhLDbuhPK8N+Rm4HIlXpumgDoyhqjXpQm4A6JoAWdkin35B40ct7FN36MS2GJTVRXvxpY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: jira-token-secret
      namespace: pminkows-cicd
    type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: rox-central-endpoint
data:
  rox_central_endpoint: Y2VudHJhbC5zdGFja3JveC5zdmM6NDQz
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: rox-api-token
data:
  rox_api_token: >-
    ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltcDNkR3N3SWl3aWRIbHdJam9pU2xkVUluMC5leUpoZFdRaU9sc2lhSFIwY0hNNkx5OXpkR0ZqYTNKdmVDNXBieTlxZDNRdGMyOTFjbU5sY3lOaGNHa3RkRzlyWlc1eklsMHNJbVY0Y0NJNk1UY3pNVFE0TlRVNU9Td2lhV0YwSWpveE5qazVPVFE1TlRrNUxDSnBjM01pT2lKb2RIUndjem92TDNOMFlXTnJjbTk0TG1sdkwycDNkQ0lzSW1wMGFTSTZJbUk1WlRKbU5HSTJMVEZqTnpFdE5EQXpOUzFoWmpGbUxXTmhaamRsTW1WbFlqbG1aaUlzSW01aGJXVWlPaUowWld0MGIyNHRZWEJwTFhSdmEyVnVJaXdpY205c1pYTWlPbHNpUVdSdGFXNGlYWDAuWFNMdkZuaXZzMV9mNTJEQTZUakd0akdNOWFOV2w3LUpHbEFUVDYtS2cxQ1R5YmZBSUNXV1U2czhvZmRhSGlFSzVNUmtyd19BcXY5VFg2S00tbUFyN3NNRHFqX0F3OGhsWHR6QVdRMVFXdy1hNVNFbFVkckllZ0dVM3ZpMjBIVG1BYWJHTG14OC1KLTJ6UHNmSWQzTmkteHUxUEhIakNPNXBaalNfSUtjcWpkbURCUmQ5X2d1ekx1TExXaXlKaWQwb000MTJDaEJycGpzakVSSWc0RDV1SEJPN1JzVWh6U1BrWDdsUEpvdWVYR3l0OURCZGE3c1liOVBzbVFScE1PUlJzY2ppcTNWcGRtSDl4dC0ydzdkVjZadmFGLVBZaEFRNG5RVjZZOTYyMTBINEk4eDlyNGFuWTFWMllXaFZzLTlHaXBFVUJTbnJ1N1Rzczh1SDUzRUthX0thNFhEUHI3X3FBeDc0b3BpcXJ3d2Vaa0l5RjgzUFM4TEFlSHlmb0o4RlhGMlhHSU92d21MSkJWV20zaWllNWFKSjNhSUxHWElIQ1YyRUZUemkza0FBYy0tcjdNd2hEN1UxdFBiaDB3WWFJclF6ZWhKcW1aSjNnNTVzRkhVdnFJdkZJd1B1UHNhREJxd2hxeHZBZ0xPZlZIRWUtS01tNkRLeFVuMlQzcVM0RkhvdGgwbXJfYXdFUFVRVXE3X3hILU1fOEloUVpKNElrOXZ0QWpyY0dzTDh3Q2t5aWZ6V2ZqQjQwS3kzQ2VJQWZlLURqY3J6Ujg1Wkd5Q3NoeHhROHFtanFxeDFoaUlJTU9PX1l5WDZkdy1DTHBjWHZ1RDJZdlZnb0YtSGpFdTFINEZhUmNwaXZMM3J5bV9WRkZtTHF0VnFKNmNBa1BoREtzenZyRjg5aHM=
type: Opaque