apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: example
      secretKey: example
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gitlab-properties-on-openshift