apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            key: token
            name: external-secrets-token
      environment: test
      projectID: '30263557'
