apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-secrets-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCaSh3ZlBYbb+5Cw3egdRYJG9u85b03EXlgg5ipUsPNcjy/6ZXpGUW12O/UAkwUWvUrRPAw5aFU/tcqFGaRqIoW16ScXL+vrOYb/JWSSHg6NZwF1kHE7zA/LwDAyHd5Hhtw1vgA/fKYXTBPr2+aM2US1+4ISruysXxcOujoRHt75tqbyjmlZOuHBpNhSPeasjp6GaS9DcUvI39sZiHdr7CN8uTO5mu8UW1H/xZMwHdoxCVixDBftQ9AzKL20jPbnIlXl8efExweN/Q1t+5kRXIKQiF75F8UqeOgDou0gCQ8lkJ2fatxWS465Eh0fCxkXMt+jlEKV4ezVYXWz1wEiZ/rph1BbYvShrXHm/veNwRWWMd1C5FhBDIRMTTDVaNu91+czpPpdw2xJwhtqINnge8+00ilRxwx6xBqzq53D1mq/orJ5NplMYCmV2POoeY+Xvluzpiq+pg0Kp4nSvsIfL6CkKYp2bbZw0nSjoH5qFT+ESJHRfiUCrYZ3vUU5mNDQlXdLfzide4ZF1dwu65kxZcirnanVWhESKKR7ltN2DaD/Gvzk2d8LGfOoZ95IlMddi2QyeO9RvXuuCTrJHcyTo1gWsteb8oP9jLrbF0Ynau/EX+IE03HVV2SYWGsJOjEDTBv3idYfG8wxGTAJ5GyrK/9cEu0zaEYtUWe/Ok1nvBvE6z4f3CjMaA4KiebyeqwXYmqAdFjO+MLs63MW8dzRd151wr6l77nTA1okA==
  template:
    metadata:
      creationTimestamp: null
      name: external-secrets-token
      namespace: external-secrets
    type: Opaque

