apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acm
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-init
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-global
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'cluster-init-{{name}}'
    spec:
      destination:
        server: '{{server}}'
      project: acm
      source:
        path: global
        repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
        targetRevision: master
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-init
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-global
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'demo-init-{{name}}'
    spec:
      destination:
        server: '{{server}}'
      project: acm
      source:
        helm:
          valueFiles:
            - values-remote.yaml
        path: clusters
        repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
        targetRevision: master
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: acm
  source:
    helm:
      valueFiles:
        - values-aws-1.yaml
    path: acm
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: acm
  source:
    helm:
      valueFiles:
        - values-gcp-1.yaml
    path: acm
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: demo-global
  namespace: openshift-gitops
spec:
  clusterSet: demo-global
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo-global
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
    cluster: openshift-gitops
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: demo-global
    namespace: openshift-gitops
