apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: Namespace
apiVersion: v1
metadata:
  name: interconnect
  labels:
    openshift.io/cluster-monitoring: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: skupper-site
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMVENDQWhXZ0F3SUJBZ0lSQUlIdGNqMklWYmdnQjJJN2JhenRaSjR3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUI0WERUSXpNVEl4TVRJeE1EUXhNRm9YRFRJNApNVEl3T1RJeE1EUXhNRm93R2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc29rSDNOT2Z2VkNZYmdjc2VobXNkYnNNbHNCa2tUWTEKSUpubnRRYlEyMzlzMytRTDdzZ3BjL0VxVHV3M3pxdjlwc0Npb3RFajd6cmV6Qmk0REo0UThlcFIySXJsMzh4TwpRSEhFYmdWMXczTXhSVWJKVVBaUjIrSmhEV21Hbll2VTZFTlFkSmVUcHNTWkZEQmdLM1d2SmxIbG9iQmpFYlBPCjcreWcyRzFmWjNmS0JDZEhlYm1hS05yRFFmQkRYUFNLTHdkeFU4Sk9GV3pTV1ZwMnp3YlhmV2NnTHNmM3BVeHQKMGRZY3RqWXBqSk43b05RTldBalpnUlRobEJxbjNlOUZKeVpDRXk2c0htaHN0aUc1VnlMNTRXZzRWNk95ZTFIUwpadXdxYTdGVnY2cURKWnoycUFYem9GdW9vOXRRaG01aDA1bEVkME5QclhpRnhubURjMlc0YVFJREFRQUJvMjR3CmJEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkxqcGREQ3ExaWk1N0NDWnN3TWhvR0VUUkxCNwpNQXNHQTFVZEVRUUVNQUtDQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU5GbC9NeFF4NXQycktoSHcrUndECnZBVkp5YWhyZ212MnRRNkw0L3RJQUd4V3Y2VXFyOFhmeUVteUdudWFicEtndWFvekdIeXlxRlk4TDJrRHViZUQKWHE4VU9namphQlhONkJ5bFJyaDZOTFRSYjBJanVRWmt0clhLOXZpK09HUWhBT2RCKzQxalFkQnRzMmpqM1VSZApsTjU4bUV4Y3lNemdWL0NzcEJ0WThQZjVoeDVUK0tLdzJDU0Q4azRSaEhxbzFpcXB5T1JwbnJ2L05sd1drQWgvCndoaFQvMEJsZ3dnb2VqTS91bHdZRzdQbWZQbVZ5OGcvellRTmp6eXNMQjlqdkdTcmU0bmh1ZlZ5UjM0ZG0vN3cKTjVtQkxXT1c1QkxXaldZaitOWVkwejZndTlOM0xHT2c3Q2VRWmVIcUExdUJQMVBvODFFT0ZFSjYvNHFtcU9vQwpWUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  password: MVg2OFJJYmVidWQ2ZWdzcE9QWENNMURI
kind: Secret
metadata:
  annotations:
    skupper.io/generated-by: 3abdad92-3ee3-457f-9aea-c6ebcb36eaf3
    skupper.io/site-version: 1.4.4-rh-1
    skupper.io/url: https://claims-interconnect.apps.olpv5h0221b6a20e39.eastus.aroapp.io:443/b2c8c2f4-98d0-11ee-90c4-acde48001122
  creationTimestamp: null
  labels:
    skupper.io/type: token-claim
  name: token-req
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: prometheus-operator
  name: sample-kotlin-spring
  namespace: interconnect
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /actuator/prometheus
      targetPort: 8080
  selector:
    matchLabels:
      app: sample-kotlin-spring
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interconnect-read
  namespace: interconnect
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interconnect-prometheus-k8s-read-binding
  namespace: interconnect
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: interconnect-read