clusterName: gcp-1
baseDomain: openshiftcorp.dev
region: europe-west1
project: openshift-366120
provider: Google
workerType: n1-standard-4
workerReplicas: 3
managedSet: demo-global
version: 4.12.25
autoscaling: false